### ISSUE TITLE
Coordinates are displayed as 0.00

### ISSUE THREAD

**Issue by karimi81** [YaoLab-Bioinfo/shinyCircos#15]
Hi There,
I am trying to use shinyCircos to draw a circos. When I upload the data of gene rate (as line type), I see that the start and end columns display 0.000 and there is no actual value for them. I tried to use tab delimited, space-delimited and comma-delimited formats but it did not work. I also changed these columns to be numeric in R but it does not still work.:
![image](https://user-images.githubusercontent.com/47839623/140153082-2bbb6a47-790b-4e18-b308-6011a2e22519.png)

**Comment by yimingfish** [comment]
Hi, could you paste the screenshot of your actual data or provide your data file?

**Comment by Karimi-81** [comment]
Hi, thank you for your reply. I decreased the number of windows (1Mb windows instead of 20kb) and the data could be read correctly. It seems that it was just about loading the huge data set.
